scraper-settings:
    websitesSettings:
        linkedin:
            baseUrl: https://www.linkedin.com/
            availableHeaders:
                - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
            extraHeaders: [ ]
            customProperties: []

        amazon:
            baseUrl: https://www.amazon.it
            availableHeaders:
                - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
            extraHeaders: [ ]
            customProperties:
                searchUrl: https://www.amazon.it/
        tcgstore:
            base-url: https://tcg-store.it/
            availableHeaders:
              - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
            extraHeaders: [ ]
            customProperties:
                find-summary-products: https://tcg-store.it/home/giochi-di-carte/
        steam:
            base-url: https://steamcommunity.com
            availableHeaders:
                - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
            extraHeaders: [ ]
            customProperties: []

tracking:
    defaultRegistrationExpireTime: 1 # minutes
    defaultScheduleInterval: 5000 # milliseconds

logging:
    level:
        root: info

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopapi
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
#spring.jpa.show-sql: true