scraper-settings:
    websitesSettings:
        trovaPrezzi:
            availableHeaders:
                - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
            extraHeaders: []
            customProperties:
                urlFreeSearch: https://www.trovaprezzi.it/categoria.aspx?id=-1&libera=



logging:
    level:
        root: info