openapi: 3.0.3
info:
  title: ShopAPI
  description: scrappone
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /tcg-store/find-summary-products:
    post:
      tags:
        - tcg-store
      operationId: findSummaryProducts
      x-scrape-api: array
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pageNum:
                  type: integer
                query:
                  type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TcgProductsTracked'
  /amazon/find-product-details:
    post:
      tags:
        - amazon
      summary: Find amazon product details
      description: Find amazon product details
      operationId: findProductDetails
      x-scrape-api: object
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonProductTracked'
  /steam/profile:
    post:
      tags:
        - Steam
      summary: Find steam profile info
      description: Find steam profile info
      operationId: findSteamProfile
      x-scrape-api: object
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SteamProfileTracked'
  /tracking/{trackingId}/listen:
    post:
      tags:
        - tracking
      summary: Register a webhook for this tracking id
      description: Register a webhook for this tracking id
      operationId: listenTrackingWebhook
      parameters:
        - in: path
          name: trackingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterWebhookRequest'
      responses:
        '200':
          description: OK
  /tracking/{trackingId}/unlisten:
    delete:
      tags:
        - tracking
      summary: Remove webhook for this tracking id
      description: Remove webhook for this tracking id
      operationId: unlistenTrackingWebhook
      parameters:
        - in: path
          name: trackingId
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK

components:
  schemas:
    TcgProductsTracked:
      type: object
      properties:
        items:
          items:
            $ref: '#/components/schemas/TcgProductDto'
        track:
          $ref: '#/components/schemas/ProductTrackingDto'

    AmazonProductTracked:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/AmazonProductDto'
        track:
          $ref: '#/components/schemas/ProductTrackingDto'

    SteamProfileTracked:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/SteamProfileDto'
        track:
          $ref: '#/components/schemas/ProductTrackingDto'

    SteamProfileDto:
      type: object
      x-dqueriable:
        id-composition: [name]
      properties:
        name:
          type: string
        online:
          type: boolean
        playingAt:
          type: string

    TcgProductDto:
      type: object
      x-dqueriable:
        id-composition: [url]
      properties:
        name:
          type: string
        img:
          type: string
        url:
          type: string
        oldPrice:
          type: number
          format: double
        newPrice:
          type: number
          format: double
        category:
          type: string
        soldOut:
          type: boolean

    AmazonProductDto:
      type: object
      x-dqueriable:
        id-composition: [name]
      properties:
        name:
          type: string
        lastPrice:
          type: number
          format: double
          description: for offer type products
        currentPrice:
          type: number
          format: double
          description: share
        savingPrice:
          type: number
          format: double
          description: for offer type products
        suggestedPrice:
          type: number
          format: double
          description: suggested price of product

    RegisterWebhookRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
        query:
          type: dquerynodeT

    ProductTrackingDto:
      type: object
      properties:
        trackingId:
          type: string
        webhookRegisterExpiresAt:
          type: string
          format: date-time