openapi: 3.0.3
info:
  title: ShopAPI
  description: scrappone
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /amazon/find-product-details:
    post:
      tags:
        - amazon
      summary: Find amazon product details
      description: Find amazon product details
      operationId: findProductDetails
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonProductTracked'
  /tracking/{trackingId}/register-webhook:
    post:
      tags:
        - tracking
      summary: Register a webhook for this tracking id
      description: Register a webhook for this tracking id
      operationId: registerTrackingWebhook
      parameters:
        - in: path
          name: trackingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterWebhookRequest'
      responses:
        '200':
          description: OK
  /tracking/{trackingId}/deregister-webhook:
    delete:
      tags:
        - tracking
      summary: Remove webhook for this tracking id
      description: Remove webhook for this tracking id
      operationId: unregisterTrackingWebhook
      parameters:
        - in: path
          name: trackingId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    AmazonProductTracked:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/AmazonProductDto'
        track:
          $ref: '#/components/schemas/ProductTrackingDto'

    AmazonProductDto:
      type: object
      x-dqueriable: true
      properties:
        name:
          type: string
        lastPrice:
          type: string
          description: for offer type products
        currentPrice:
          type: string
          description: share
        savingPrice:
          type: string
          description: for offer type products
        suggestedPrice:
          type: string
          description: suggested price of product

    RegisterWebhookRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string

    ProductTrackingDto:
      type: object
      properties:
        id:
          type: string
        webhookRegisterExpiresAt:
          type: string
          format: date-time