openapi: 3.0.3
info:
  title: ShopAPI
  description: scrappone
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /linkedin/find-candidates:
    post:
      tags:
        - linkedin
      operationId: findCandidates
      parameters:
        - $ref: '#/components/parameters/WebhookUrl'
        - $ref: '#/components/parameters/WsEnabled'
        - $ref: '#/components/parameters/CheckMode'
        - $ref: '#/components/parameters/SaveMode'
        - $ref: '#/components/parameters/PropertiesToCheck'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pageSize:
                  type: integer
                url:
                  type: string
                query:
                  type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkedinCandidatesTracked'

  /tcg-store/find-summary-products:
    post:
      tags:
        - tcg-store
      operationId: findSummaryProducts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pageNum:
                  type: integer
                query:
                  type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TcgProductDto'
  /tcg-store/find-summary-products/track:
    post:
      tags:
        - tcg-store
      operationId: findSummaryProductsTrack
      parameters:
        - $ref: '#/components/parameters/WebhookUrl'
        - $ref: '#/components/parameters/WsEnabled'
        - $ref: '#/components/parameters/CheckMode'
        - $ref: '#/components/parameters/SaveMode'
        - $ref: '#/components/parameters/PropertiesToCheck'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pageNum:
                  type: integer
                query:
                  type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TcgProductsTracked'

  /amazon/find-product-details:
    post:
      tags:
        - amazon
      summary: Find amazon product details
      description: Find amazon product details
      operationId: findProductDetails
      parameters:
        - in: query
          required: true
          name: url
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonProductDto'
  /amazon/find-product-details/track:
    post:
      tags:
        - amazon
      summary: Find amazon product details
      description: Find amazon product details
      operationId: findProductDetailsTrack
      parameters:
        - in: query
          required: true
          name: url
          schema:
            type: string
        - $ref: '#/components/parameters/WebhookUrl'
        - $ref: '#/components/parameters/WsEnabled'
        - $ref: '#/components/parameters/CheckMode'
        - $ref: '#/components/parameters/SaveMode'
        - $ref: '#/components/parameters/PropertiesToCheck'
      requestBody:
        content:
          application/json:
            schema:
              type: dquery
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonProductTracked'

  /steam/profile:
    post:
      tags:
        - Steam
      summary: Find steam profile info
      description: Find steam profile info
      operationId: findSteamProfile
      parameters:
        - in: query
          required: true
          name: url
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SteamProfileDto'
  /steam/profile/track:
    post:
      tags:
        - Steam
      summary: Find steam profile info
      description: Find steam profile info
      operationId: findSteamProfileTrack
      parameters:
        - in: query
          required: true
          name: url
          schema:
            type: string
        - $ref: '#/components/parameters/WebhookUrl'
        - $ref: '#/components/parameters/WsEnabled'
        - $ref: '#/components/parameters/CheckMode'
        - $ref: '#/components/parameters/SaveMode'
        - $ref: '#/components/parameters/PropertiesToCheck'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SteamProfileTracked'

  /tracking/{trackerId}/unlisten:
    delete:
      tags:
        - tracker
      summary: Remove webhook for this tracking id
      description: Remove webhook for this tracking id
      operationId: unlistenTrackerWebhook
      parameters:
        - in: path
          name: trackerId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

components:
  schemas:
    LinkedinCandidatesTracked:
      type: object
      properties:
        items:
          items:
            $ref: '#/components/schemas/LinkedinCandidateDto'
        track:
          $ref: '#/components/schemas/TrackerInfoDto'

    TcgProductsTracked:
      type: object
      properties:
        items:
          items:
            $ref: '#/components/schemas/TcgProductDto'
        track:
          $ref: '#/components/schemas/TrackerInfoDto'

    AmazonProductTracked:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/AmazonProductDto'
        track:
          $ref: '#/components/schemas/TrackerInfoDto'

    SteamProfileTracked:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/SteamProfileDto'
        track:
          $ref: '#/components/schemas/TrackerInfoDto'

    SteamProfileDto:
      type: object
      x-dqueriable:
        id-composition: [ name ]
      properties:
        name:
          type: string
        online:
          type: boolean
        playingAt:
          type: string

    LinkedinCandidateDto:
      type: object
      x-dqueriable:
        id-composition: [ id ]
      properties:
        id:
          type: string
        name:
          type: string
        profileImg:
          type: string
        profileUrl:
          type: string
        memberDistance:
          type: string
        subtitle:
          type: string
        currentOccupation:
          type: string
        city:
          type: string
        mutualConnections:
          type: integer

    TcgProductDto:
      type: object
      x-dqueriable:
        id-composition: [ url ]
      properties:
        name:
          type: string
        img:
          type: string
        url:
          type: string
        oldPrice:
          type: number
          format: double
        newPrice:
          type: number
          format: double
        category:
          type: string
        soldOut:
          type: boolean

    AmazonProductDto:
      type: object
      x-dqueriable:
        id-composition: [ name ]
      properties:
        name:
          type: string
        lastPrice:
          type: number
          format: double
          description: for offer type products
        currentPrice:
          type: number
          format: double
          description: share
        savingPrice:
          type: number
          format: double
          description: for offer type products
        suggestedPrice:
          type: number
          format: double
          description: suggested price of product

    TrackerInfoDto:
      type: object
      properties:
        trackerId:
          type: string

  parameters:
    WebhookUrl:
      in: query
      required: false
      name: webhookUrl
      schema:
        type: string
    WsEnabled:
      in: query
      required: false
      name: wsEnabled
      schema:
        type: boolean
    CheckMode:
      in: query
      required: false
      name: checkMode
      schema:
        type: dcheckmode
    SaveMode:
      in: query
      required: false
      name: saveMode
      schema:
        type: dsavemode
    PropertiesToCheck:
      in: query
      required: false
      name: propertiesToCheck
      schema:
        items:
          type: string

