openapi: 3.0.3
info:
  title: ShopAPI
  description: scrappone
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /trovaprezzi/search-products:
    get:
      tags:
        - trovaprezzi
      summary: Find trovaprezzi products
      description: Find trovaprezzi products
      operationId: searchProducts
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: category
          description: path of category including extension of the page (like .aspx) if it exists, do not include base path
          required: true
          schema:
            type: integer
            minimum: 0
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
        - in: query
          name: filters
          description: each category can have their own filters, check on the page itself and add the one needed
          schema:
            type: array
            items:
              type: string
        - in: query
          name: minPrice
          schema:
            type: integer
            minimum: 1
        - in: query
          name: maxPrice
          schema:
            type: integer
        - in: query
          name: rating
          schema:
            type: integer
            minimum: 1
            maximum: 5
        - in: query
          name: sort
          schema:
            $ref: '#/components/schemas/TrovaPrezziSort'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrovaPrezziProduct'
  /trovaprezzi/list-categories:
    get:
      tags:
        - trovaprezzi
      summary: list trovaprezzi categories
      description: list trovaprezzi categories
      operationId: listCategories
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrovaPrezziCategory'
components:
  schemas:
    TrovaPrezziCategory:
      type: object
      additionalProperties:
        type: array
        items:
          type: string


    TrovaPrezziProduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        image_url:
          type: string
        url:
          type: string
        price:
          type: string
        delivery_price:
          type: string
        available:
          type: boolean

    TrovaPrezziSort:
      enum: ["cheapest", "unpopular"]
      type: string